services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    volumes:
      - "{{ xray_db_path }}/:/etc/x-ui/"
      - "{{ cert_path }}/live/{{ domain_name }}/fullchain.pem:/fullchain.pem"
      - "{{ cert_path }}/live/{{ domain_name }}/privkey.pem:/privkey.pem"
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "true"
    tty: true
    network_mode: host
    restart: unless-stopped