services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:v2.0.2
    container_name: 3x-ui
    hostname: yourhostname
    volumes:
      - $PWD/db/:/etc/x-ui/
      - /public.key:/public.key
      - /private.key:/private.key
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped

