PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
--INSERT INTO users VALUES(1,'root','zekve4-wybKik-dymsib','');
UPDATE users SET username='root', password='zekve4-wybKik-dymsib', login_secret='';
--INSERT INTO settings VALUES(1,'secret','inOMWF6DwawVxgpuQ5Q62Ly4RJ83HDfS');
INSERT INTO settings VALUES(2,'webListen','');
INSERT INTO settings VALUES(3,'webDomain','');
INSERT INTO settings VALUES(4,'webPort','39866');
INSERT INTO settings VALUES(5,'webCertFile','/public.key');
INSERT INTO settings VALUES(6,'webKeyFile','/private.key');
INSERT INTO settings VALUES(7,'webBasePath','/tffklncvuf/');
INSERT INTO settings VALUES(8,'sessionMaxAge','0');
INSERT INTO settings VALUES(9,'pageSize','0');
INSERT INTO settings VALUES(10,'expireDiff','0');
INSERT INTO settings VALUES(11,'trafficDiff','0');
INSERT INTO settings VALUES(12,'remarkModel','-ieo');
INSERT INTO settings VALUES(13,'tgBotEnable','false');
INSERT INTO settings VALUES(14,'tgBotToken','');
INSERT INTO settings VALUES(15,'tgBotChatId','');
INSERT INTO settings VALUES(16,'tgRunTime','@daily');
INSERT INTO settings VALUES(17,'tgBotBackup','false');
INSERT INTO settings VALUES(18,'tgBotLoginNotify','true');
INSERT INTO settings VALUES(19,'tgCpu','0');
INSERT INTO settings VALUES(20,'tgLang','en-US');
INSERT INTO settings VALUES(21,'timeLocation','Asia/Tehran');
INSERT INTO settings VALUES(22,'secretEnable','false');
INSERT INTO settings VALUES(23,'subEnable','true');
INSERT INTO settings VALUES(24,'subListen','');
INSERT INTO settings VALUES(25,'subPort','2096');
INSERT INTO settings VALUES(26,'subPath','/s/');
INSERT INTO settings VALUES(27,'subDomain','');
INSERT INTO settings VALUES(28,'subCertFile','/public.key');
INSERT INTO settings VALUES(29,'subKeyFile','/private.key');
INSERT INTO settings VALUES(30,'subUpdates','1');
INSERT INTO settings VALUES(31,'subEncrypt','true');
INSERT INTO settings VALUES(32,'subShowInfo','true');
INSERT INTO settings VALUES(33,'subURI','');
INSERT INTO settings VALUES(34,'xrayTemplateConfig',replace('{\n  "log": {\n    "loglevel": "warning",\n    "error": "./error.log"\n  },\n  "api": {\n    "tag": "api",\n    "services": [\n      "HandlerService",\n      "LoggerService",\n      "StatsService"\n    ]\n  },\n  "inbounds": [\n    {\n      "tag": "api",\n      "listen": "127.0.0.1",\n      "port": 62789,\n      "protocol": "dokodemo-door",\n      "settings": {\n        "address": "127.0.0.1"\n      }\n    }\n  ],\n  "outbounds": [\n    {\n      "protocol": "freedom",\n      "settings": {}\n    },\n    {\n      "tag": "blocked",\n      "protocol": "blackhole",\n      "settings": {}\n    },\n    {\n      "tag": "IPv4",\n      "protocol": "freedom",\n      "settings": {\n        "domainStrategy": "UseIPv4"\n      }\n    },\n    {\n      "tag": "WARP",\n      "protocol": "socks",\n      "settings": {\n        "servers": [\n          {\n            "address": "127.0.0.1",\n            "port": 40000\n          }\n        ]\n      }\n    }\n  ],\n  "policy": {\n    "levels": {\n      "0": {\n        "statsUserDownlink": true,\n        "statsUserUplink": true\n      }\n    },\n    "system": {\n      "statsInboundDownlink": true,\n      "statsInboundUplink": true\n    }\n  },\n  "routing": {\n    "domainStrategy": "IPIfNonMatch",\n    "rules": [\n      {\n        "type": "field",\n        "inboundTag": [\n          "api"\n        ],\n        "outboundTag": "api"\n      },\n      {\n        "type": "field",\n        "outboundTag": "blocked",\n        "ip": [\n          "geoip:private"\n        ]\n      },\n      {\n        "type": "field",\n        "outboundTag": "blocked",\n        "protocol": [\n          "bittorrent"\n        ]\n      },\n      {\n        "type": "field",\n        "outboundTag": "IPv4",\n        "domain": [\n          "geosite:google"\n        ]\n      },\n      {\n        "type": "field",\n        "domain": [\n          "geosite:category-gov-ru",\n          "regexp:.*\\.ru$",\n          "geosite:openai"\n        ],\n        "outboundTag": "WARP"\n      },\n      {\n        "type": "field",\n        "ip": [\n          "geoip:ru"\n        ],\n        "outboundTag": "WARP"\n      },\n      {\n        "type": "field",\n        "ip": [\n          "geoip:by"\n        ],\n        "outboundTag": "WARP"\n      },\n      {\n        "type": "field",\n        "ip": [\n          "109.196.164.162"\n        ],\n        "outboundTag": "WARP"\n      },\n      {\n        "type": "field",\n        "domain": [\n          "*.ruvds.com"\n        ],\n        "outboundTag": "WARP"\n      }\n    ]\n  },\n  "stats": {}\n}','\n',char(10)));
INSERT INTO client_traffics VALUES(4,2,1,'city',0,0,0,0,0);
-- generate short id, certs 
INSERT INTO inbounds VALUES(1,1,0,0,0,'flag',1,0,'ip',443,'vless',replace('{\n  "clients": [\n    {\n      "email": "Istanbul",\n      "enable": true,\n      "expiryTime": 0,\n      "flow": "xtls-rprx-vision",\n      "id": "5b19a9c6-bd17-49a7-83b2-29e3e7ab263b",\n      "limitIp": 0,\n      "reset": 0,\n      "subId": "guerfqg7427cf3os",\n      "tgId": "",\n      "totalGB": 0\n    }\n  ],\n  "decryption": "none",\n  "fallbacks": []\n}','\n',char(10)),replace('{\n  "network": "tcp",\n  "security": "reality",\n  "externalProxy": [],\n  "realitySettings": {\n    "show": false,\n    "xver": 0,\n    "dest": "amazon.com.tr:443",\n    "serverNames": [\n      "amazon.com.tr",\n      "www.amazon.com.tr"\n    ],\n    "privateKey": "2Ed66qnwfWkbtSYwnsJGgztCkTU5VxvCbjhLNjqjSHQ",\n    "minClient": "",\n    "maxClient": "",\n    "maxTimediff": 0,\n    "shortIds": [\n      "9ba38049"\n    ],\n    "settings": {\n      "publicKey": "XljeLY63MYNUUcU4lSXNdQACMdYa5T6svl0gMB_eeAs",\n      "fingerprint": "chrome",\n      "spiderX": "/"\n    }\n  },\n  "tcpSettings": {\n    "acceptProxyProtocol": false,\n    "header": {\n      "type": "none"\n    }\n  }\n}','\n',char(10)),'inbound-443',replace('{\n  "enabled": true,\n  "destOverride": [\n    "http",\n    "tls",\n    "quic",\n    "fakedns"\n  ]\n}','\n',char(10)),NULL);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('users',1);
INSERT INTO sqlite_sequence VALUES('settings',34);
INSERT INTO sqlite_sequence VALUES('client_traffics',4);
INSERT INTO sqlite_sequence VALUES('inbounds',2);
COMMIT;
