PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
UPDATE users SET username='root', password='zekve4-wybKik-dymsib', login_secret='';
INSERT OR REPLACE INTO settings VALUES(2,'webListen','');
INSERT OR REPLACE INTO settings VALUES(3,'webDomain','');
INSERT OR REPLACE INTO settings VALUES(4,'webPort','39866');
INSERT OR REPLACE INTO settings VALUES(5,'webCertFile','/fullchain.pem');
INSERT OR REPLACE INTO settings VALUES(6,'webKeyFile','/privkey.pem');
INSERT OR REPLACE INTO settings VALUES(7,'webBasePath','/tffklncvuf/');
INSERT OR REPLACE INTO settings VALUES(8,'sessionMaxAge','0');
INSERT OR REPLACE INTO settings VALUES(9,'pageSize','0');
INSERT OR REPLACE INTO settings VALUES(10,'expireDiff','0');
INSERT OR REPLACE INTO settings VALUES(11,'trafficDiff','0');
INSERT OR REPLACE INTO settings VALUES(12,'remarkModel','-ieo');
INSERT OR REPLACE INTO settings VALUES(13,'tgBotEnable','false');
INSERT OR REPLACE INTO settings VALUES(14,'tgBotToken','');
INSERT OR REPLACE INTO settings VALUES(15,'tgBotChatId','');
INSERT OR REPLACE INTO settings VALUES(16,'tgRunTime','@daily');
INSERT OR REPLACE INTO settings VALUES(17,'tgBotBackup','false');
INSERT OR REPLACE INTO settings VALUES(18,'tgBotLoginNotify','true');
INSERT OR REPLACE INTO settings VALUES(19,'tgCpu','0');
INSERT OR REPLACE INTO settings VALUES(20,'tgLang','en-US');
INSERT OR REPLACE INTO settings VALUES(21,'timeLocation','Asia/Tehran');
INSERT OR REPLACE INTO settings VALUES(22,'secretEnable','false');
INSERT OR REPLACE INTO settings VALUES(23,'subEnable','true');
INSERT OR REPLACE INTO settings VALUES(24,'subListen','');
INSERT OR REPLACE INTO settings VALUES(25,'subPort','2096');
INSERT OR REPLACE INTO settings VALUES(26,'subPath','/s/');
INSERT OR REPLACE INTO settings VALUES(27,'subDomain','');
INSERT OR REPLACE INTO settings VALUES(28,'subCertFile','/fullchain.pem');
INSERT OR REPLACE INTO settings VALUES(29,'subKeyFile','/privkey.pem');
INSERT OR REPLACE INTO settings VALUES(30,'subUpdates','1');
INSERT OR REPLACE INTO settings VALUES(31,'subEncrypt','true');
INSERT OR REPLACE INTO settings VALUES(32,'subShowInfo','true');
INSERT OR REPLACE INTO settings VALUES(33,'subURI','');
INSERT OR REPLACE INTO settings VALUES(34,'xrayTemplateConfig',replace('{\n  "log": {\n    "loglevel": "warning",\n    "error": "./error.log"\n  },\n  "api": {\n    "tag": "api",\n    "services": [\n      "HandlerService",\n      "LoggerService",\n      "StatsService"\n    ]\n  },\n  "inbounds": [\n    {\n      "tag": "api",\n      "listen": "127.0.0.1",\n      "port": 62789,\n      "protocol": "dokodemo-door",\n      "settings": {\n        "address": "127.0.0.1"\n      }\n    }\n  ],\n  "outbounds": [\n    {\n      "protocol": "freedom",\n      "settings": {}\n    },\n    {\n      "tag": "blocked",\n      "protocol": "blackhole",\n      "settings": {}\n    },\n    {\n      "tag": "IPv4",\n      "protocol": "freedom",\n      "settings": {\n        "domainStrategy": "UseIPv4"\n      }\n    },\n    {\n      "tag": "WARP",\n      "protocol": "socks",\n      "settings": {\n        "servers": [\n          {\n            "address": "127.0.0.1",\n            "port": 40000\n          }\n        ]\n      }\n    }\n  ],\n  "policy": {\n    "levels": {\n      "0": {\n        "statsUserDownlink": true,\n        "statsUserUplink": true\n      }\n    },\n    "system": {\n      "statsInboundDownlink": true,\n      "statsInboundUplink": true\n    }\n  },\n  "routing": {\n    "domainStrategy": "IPIfNonMatch",\n    "rules": [\n      {\n        "type": "field",\n        "inboundTag": [\n          "api"\n        ],\n        "outboundTag": "api"\n      },\n      {\n        "type": "field",\n        "outboundTag": "blocked",\n        "ip": [\n          "geoip:private"\n        ]\n      },\n      {\n        "type": "field",\n        "outboundTag": "blocked",\n        "protocol": [\n          "bittorrent"\n        ]\n      },\n      {\n        "type": "field",\n        "outboundTag": "IPv4",\n        "domain": [\n          "geosite:google"\n        ]\n      },\n      {\n        "type": "field",\n        "domain": [\n          "geosite:category-gov-ru",\n          "regexp:.*\\.ru$",\n          "geosite:openai"\n        ],\n        "outboundTag": "WARP"\n      },\n      {\n        "type": "field",\n        "ip": [\n          "geoip:ru"\n        ],\n        "outboundTag": "WARP"\n      },\n      {\n        "type": "field",\n        "ip": [\n          "geoip:by"\n        ],\n        "outboundTag": "WARP"\n      },\n      {\n        "type": "field",\n        "ip": [\n          "109.196.164.162"\n        ],\n        "outboundTag": "WARP"\n      },\n      {\n        "type": "field",\n        "domain": [\n          "*.ruvds.com"\n        ],\n        "outboundTag": "WARP"\n      }\n    ]\n  },\n  "stats": {}\n}','\n',char(10)));
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('users',1);
INSERT INTO sqlite_sequence VALUES('settings',34);
INSERT INTO sqlite_sequence VALUES('client_traffics',4);
INSERT INTO sqlite_sequence VALUES('inbounds',2);
COMMIT;
