services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    network_mode: host
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
#     - WATCHTOWER_NOTIFICATION_URL=telegram://ZZZZZZZZZZ:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@telegram/?channels=XXXXXXX
# OR if youn need support topic
# in api link replace ":" with "%3A"
#   - WATCHTOWER_NOTIFICATION_URL=generic://api.telegram.org/bot{xxx}%3A{token}/sendMessage
#   - 'WATCHTOWER_NOTIFICATION_TEMPLATE={{if .}}{"text":"{{range .}}{{.Message}}\n{{end}}","chat_id":"{id}","message_thread_id":"5"}{{end}}'
    restart: unless-stopped
  exporter:
    image: registry.gitlab.com/hctrdev/fail2ban-prometheus-exporter:latest
    container_name: fail2ban_export
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro  
    - /var/run/fail2ban/:/var/run/fail2ban:ro
    ports:
    - "9191:9191"
    restart: unless-stopped